set -e
CLEOS="cleos -u https://api.jungle.alohaeos.com:443 "

$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "air", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "grass", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dirt", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cobblestone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sapling", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bedrock", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sand", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gravel", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "coal.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "log", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leaves", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sponge", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "glass", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lapis.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lapis.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dispenser", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sandstone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "note.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "powered.rail", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "detector.rai", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "piston.sti.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "web", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "long.grass", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dead.bush", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "piston.base", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wool", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "yellow.flowe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.rose", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brown.mushro", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.mushroom", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "step", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "tnt", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bookshelf", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "mossy.cobble", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "obsidian", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "torch", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "mob.spawner", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.stairs", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chest", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.bloc", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "workbench", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "soil", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "furnace", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ladder", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rails", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cobblestones", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lever", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.plate", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.plate", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone.tor", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.button", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "snow", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ice", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "snow.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cactus", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "clay", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jukebox", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pumpkin", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "netherrack", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "soul.sand", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "glowstone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jack.o.lante", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stained.glas", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "trap.door", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "monster.eggs", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "smooth.brick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "huge.mus.1", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "huge.mus.2", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "thin.glass", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "melon.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "vine", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "fence.gate", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brick.stairs", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "smooth.stair", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "mycel", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "water.lily", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.brick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.bri.s", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "enchantmentt", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ender.por.fr", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ender.stone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dragon.egg", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone.lam", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.step", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sandstone.st", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "emerald.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ender.chest", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "tripwire.hoo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "emerald.bloc", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spruce.woo.s", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "birch.woo.st", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jungle.woo.s", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "command", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "beacon", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cobble.wall", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.button", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "anvil", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "trapped.ches", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.plate", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.plate", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "daylight.det", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone.blo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "quartz.ore", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "hopper", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "quartz.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "quartz.stair", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "activator.ra", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dropper", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stained.clay", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stained.glap", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leaves.2", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "log.2", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "acacia.stair", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dark.oak.sta", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "slime.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "barrier", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.trapdoo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "prismarine", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sea.lantern", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "hay.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "carpet", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "hard.clay", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "coal.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "packed.ice", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "double.plant", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.sandston", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.san.stai", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.slab2", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spruce.fen.g", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "birch.fen.ga", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jungle.fen.g", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dark.oak.fen", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "acacia.fen.g", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spruce.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "birch.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jungle.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dark.oak.fen", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "acacia.fence", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "end.rod", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chorus.plant", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chorus.flowe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purpur.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purpur.pilla", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purpur.stair", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purpur.slab", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "end.bricks", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "grass.path", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "command.repe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "command.chai", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "magma", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.war.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.net.bric", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bone.block", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "structure.vo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "observer", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "white.shu.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "orange.shu.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "magenta.shub", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "light.blu.sh", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "yellow.shu.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lime.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pink.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gray.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "silver.shu.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cyan.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purple.shu.b", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "blue.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brown.shu.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "green.shu.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.shu.box", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "black.shu.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "white.gla.te", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "orange.gla.t", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "magenta.glat", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "light.blu.gl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "yellow.gla.t", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lime.gla.ter", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pink.gla.ter", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gray.gla.ter", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "silver.gla.t", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cyan.gla.ter", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "purple.gla.t", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "blue.gla.ter", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brown.gla.te", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "green.gla.te", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "red.gla.terr", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "black.gla.te", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "concrete", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "concrete.pow", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "structure.bl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.spade", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.pickaxe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.axe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "flint.and.st", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "apple", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bow", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "arrow", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "coal", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.ingot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.ingot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.sword", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.sword", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.spade", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.pickaxe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.axe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.sword", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.spade", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.pickax", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.axe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.swor", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.spad", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.pick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.axe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bowl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "mushroom.sou", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.sword", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.spade", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.pickaxe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.axe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "string", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "feather", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sulphur", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.hoe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "stone.hoe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.hoe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.hoe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.hoe", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "seeds", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wheat", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bread", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leather.helm", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leather.ches", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leather.legg", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leather.boot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chainmail.he", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chainmail.ch", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chainmail.le", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chainmail.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.helmet", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.chestpl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.legging", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.boots", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.helm", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.ches", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.legg", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.boot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.helmet", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.chestpl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.legging", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.boots", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "flint", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pork", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "grilled.pork", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "painting", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "golden.apple", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sign", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "wood.door", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bucket", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "water.bucket", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lava.bucket", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "minecart", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "saddle", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.door", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "snow.ball", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leather", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "milk.bucket", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "clay.brick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "clay.ball", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sugar.cane", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "paper", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "book", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "slime.ball", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "storage.mine", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "powered.mine", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "egg", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "compass", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "fishing.rod", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "watch", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "glowstone.du", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "raw.fish", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cooked.fish", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ink.sack", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bone", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "sugar", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cake", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "bed", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diode", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cookie", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "map", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "shears", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "melon", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pumpkin.seed", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "melon.seeds", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "raw.beef", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cooked.beef", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "raw.chicken", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cooked.chick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rotten.flesh", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ender.pearl", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "blaze.rod", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "ghast.tear", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.nugget", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.stalk", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "potion", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "glass.bottle", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spider.eye", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "fermented.sp", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "blaze.powder", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "magma.cream", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "brewing.stai", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cauldron.ite", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "eye.of.ender", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "speckled.mel", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "monster.egg", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "exp.bottle", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "fireball", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "book.and.qui", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "written.book", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "emerald", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "item.frame", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "flower.pot.i", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "carrot.item", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "potato.item", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "baked.potato", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "poisonous.po", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "empty.map", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "golden.carro", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "skull.item", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "carrot.stick", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.star", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "pumpkin.pie", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "firework", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "firework.cha", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "enchanted.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "redstone.com", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "nether.bri.i", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "quartz", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "explosive.mi", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "hopper.minec", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "prismarine.s", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "prismarine.c", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rabbit", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cooked.rabbi", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rabbit.stew", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rabbit.foot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "rabbit.hide", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "armor.stand", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.barding", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.barding", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "diamond.bard", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "leash", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "name.tag", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "command.mine", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "mutton", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "cooked.mutto", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "banner", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "end.crystal", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spruce.doo.i", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "birch.doo.it", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "jungle.doo.i", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "acacia.doo.i", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dark.oak.doo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chorus.fruit", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "chorus.fru.p", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "beetroot", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "beetroot.see", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "beetroot.sou", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "dragons.brea", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "splash.potio", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "spectral.arr", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "tipped.arrow", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "lingering.po", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "shield", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "elytra", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat.spruce", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat.birch", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat.jungle", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat.acacia", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "boat.dar.oak", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "totem", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "shulker.shel", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "iron.nugget", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "knowledge.bo", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "gold.record", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "green.record", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.3", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.4", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.5", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.1", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.1", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.1", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.1", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.11", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.11", true, true, true, 999999999999]' -p eosminecraft
$CLEOS push action eosminecraft create '["eosminecraft", "minecraft", "record.12", true, true, true, 999999999999]' -p eosminecraft
